### ISSUE TITLE
Can't reorder order items

### ISSUE THREAD

**Issue by georgejipa** [laravel-filament/demo#6]
OS: Windows 11
Browser: 
- Firefox 95.0.1 - http://somup.com/crlbFd0MFu
- Chrome 96 - http://somup.com/crlbFL0MFP

**Comment by blite** [comment]
I am seeing this as well, I was hoping to test reordering on various databases, as for me in my own site it does not work with mysql.  I suspect it will not work with all databases and this is due to the choice to use a json object vs a json array.  

I have only tested demo with sqlite so far

Browsers:
- Chrome Version 96.0.4664.110 (Official Build) (x86_64)
- Safari Version 15.0 (16612.1.29.41.4, 16612)


Also the ui portion of this did work on filament v2.5.12 so it must be a bug introduced since then.

**Comment by tangjh** [comment]
Check out https://github.com/laravel-filament/filament/issues/1052

**Comment by pxlrbt** [comment]
Closing this as it is currently not supported in Filament and not a bug in the demo.

**Comment by pxlrbt** [comment]
My bad. This is supported now.
